---
layout: post 
title: Binary Search Algorithms 
description: Binary Search Algorithms.
courses: {csp: {week: 1} }
comments: true 
sticky_rank: 1 
---

Notes: It's an algorithm that allows u to divide and conquer to search for your value. One key part is that we need the array to be sortedb efore we actualyl search. In your actual algorithm, we want to set the two boundaries - lowest and highest value. Looping from high to low. Compare middle value to target value. Main benefit is that it allows you to cut the time it takes to search an array. It is much faster than other methods. The best case for them is that if u find the value straight away, (if ur number is the middle value). Binary is fast because it divides the array in half and it is divide andc conquer. 

If the target is never found, it is going to return -1. 

## Popcorn Hack 1: 

C: It has to slice in the middle of the list. Linear search can be unsorted. A is wrong because it doens't have to be even. B is wrong because it can contain duplicate values. D is wrong because the value of target can equal -1. 

## Popcorn Hack 2: 

B because Binary has to be used on a sorted list. A is wrong because Binary search does not take more time. C is wrong because it is in boith linear and binary search algorithsms. D is wrong because binary search can use multiple values. 


## Popcorn Hack 3 

In [6]:
def binary_search(arr, target):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1

    return -1 


sorted_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
result = binary_search(sorted_list, 'c')
print("Index of 'c':", result)


Index of 'c': 2


## Homework Hack 

In [9]:
import pandas as pd

# Load the dataset
data = pd.read_csv("school_supplies.csv")

# Drop rows with missing values
data_cleaned = data.dropna()

# Sort the data by 'Price'
data_sorted = data_cleaned.sort_values(by="Price")

# Extract sorted prices as a list
price_list = data_sorted["Price"].tolist()

# Preview the sorted data
print("First few rows of sorted data:")
print(data_sorted.head())
print("Original row count:", len(data))
print("Cleaned row count:", len(data_cleaned))

# Binary search function
def binary_search(arr, target):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1

    return -1  # Target not found

# Prices to search for
search_prices = [1.25, 6.49, 10.00]

# Search and print results
for price in search_prices:
    result = binary_search(price_list, price)
    if result != -1:
        print(f"Price ${price:.2f} found at index {result}.")
    else:
        print(f"Price ${price:.2f} not found in the list.")


First few rows of sorted data:
        Product  Price
5        Eraser   0.50
14  Paper Clips   0.89
2        Pencil   0.99
9    Glue Stick   1.25
1           Pen   1.50
Original row count: 15
Cleaned row count: 15
Price $1.25 found at index 3.
Price $6.49 found at index 12.
Price $10.00 not found in the list.


This code first loads a CSV file containing product data and cleans it by removing any rows with missing information. It then sorts the product prices from lowest to highest and extracts these sorted prices into a list. Using binary search, the code efficiently checks if specific prices (like 1.25, 6.49, or 10.00) are in the list. Finally, it prints a message indicating whether each price was found or not, helping to quickly verify the presence of those prices in the dataset.